apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-example
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/seu-usuario/seu-repo' # Atualize com seu repositório
    targetRevision: HEAD
    path: k8s # Atualize se você colocou o arquivo em outro diretório
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
