apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-example-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-example
  template:
    metadata:
      labels:
        app: api-example
    spec:
      containers:
        - name: api-example
          image: api-example:latest # Use a imagem que você criou
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-example-service
spec:
  selector:
    app: api-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
